'use strict';

// ── Mast definitions ─────────────────────────────────────────────────────────
const mastsUS = [
  { key:'scope_atk', label:'ATK SCOPE', safeDepth:22, crushDepth:40, raiseDur:4, lowerDur:4, type:'periscope' },
  { key:'esm',       label:'ESM',       safeDepth:22, crushDepth:38, raiseDur:3, lowerDur:3, type:'esm'       },
  { key:'radar',     label:'RADAR',     safeDepth:22, crushDepth:38, raiseDur:3, lowerDur:3, type:'radar'     },
  { key:'comms',     label:'COMMS',     safeDepth:22, crushDepth:38, raiseDur:3, lowerDur:3, type:'comms'     },
];

const mastsUK = [
  { key:'scope_atk',  label:'ATK SCOPE',  safeDepth:22, crushDepth:40, raiseDur:4, lowerDur:4, type:'periscope' },
  { key:'scope_srch', label:'SRCH SCOPE', safeDepth:22, crushDepth:40, raiseDur:5, lowerDur:5, type:'periscope' },
  { key:'esm',        label:'ESM',        safeDepth:22, crushDepth:38, raiseDur:3, lowerDur:3, type:'esm'       },
  { key:'radar',      label:'RADAR',      safeDepth:22, crushDepth:38, raiseDur:3, lowerDur:3, type:'radar'     },
  { key:'comms',      label:'COMMS',      safeDepth:22, crushDepth:38, raiseDur:3, lowerDur:3, type:'comms'     },
];

// ── Shared physics constants (common across all playable vessels) ─────────────
const sh = {
  speedIncrementKts:1, speedTau:45, accelTau:45, decelTau:30, turnRateDeg:2.2, turnRateMinDeg:0.5,
  periscopeDepth:18, depthStep:60, depthHoldRepeat:0.10,
  depthTau:8.0, depthRateMax:1.8, buoyancyScale:3.6, fillRate:0.022, kFill:0.0016,
  ballast:0.0, ballastRate:0.85, buoyAccel:210, buoyDamp:0.85, vyMax:190,
  flankTransient:0.28,
  silentRunning:   { speedCap:8, noiseMult:0.55 },
  emergencyTurn:   { dur:2.2, cd:8.0, rudderDeg:35, noiseSpike:0.28 },
  crashDive:       { dur:3.5, cd:12.0, noiseSpike:0.35, tauOverride:0.4, rateMult:3.5 },
  flowNoiseDiv:32, turnNoise:0.07,
  hpa: {
    maxPressure:207, reservePressure:207, ambientPerMetre:0.1,
    controlMinRatio:1.2, ascentCostPerMetre:0.04, torpedoCost:2,
    blowFlowRate:0.5, blowReferenceBar:50, blowFlowToVy:0.4, blowFlowToFillRate:0.025,
    lpRechargeRate:0.4, hpRechargeRate:2.5, rechargeNoiseAdd:0.55,
  },
  cavitationDepthRef:380, cavitationSlope:0.018, cavitationSpike:0.22,
  torpCd:0.45, cmCd:4.5, pingCd:9.0, pingPulse:1.25,
  pingDazzle:    { duration:1.5, range:1800 },
  torpArcDeg:55, torpEnableDist:16, fireDelay:4.5,   // ~160m enable distance
  torpWireMaxRange:2780, torpWireBreakTurnDeg:90,    // ~15nm wire range
  wireMaxLaunchKts:15, wireSafeKts:15, wireStressKts:20,
  wireStressBreakTime:25, wireInstantBreakKts:22,
  periscope:     { cd:10.0, dur:4.5, revealR:3600, detectBoost:1.55, noiseSpike:0.10 },
  launchTransientRange:2000, launchTransientSus:0.35,
  pingDatumRange:5000, pingDatumSus:0.75,
  trimLevers:    { fore_ends:-2.0, control_room:-0.8, aux_section:-0.2, reactor_comp:0.0, engine_room:0.8, aft_ends:2.0 },
  trimFullAuthority:2.0, planeMinSpeed:10.0, floodFillEquiv:0.28,
  casualties: {
    coolantLeak:    { stressThreshold:15, riskPerSec:0.008, degradedRiskMult:3.0, countdown:45, fastMult:1.5, slowMult:0.5, fixChanceHigh:0.65, fixChanceLow:0.30 },
    steamLeak:      { shockChance:0.12, repairTime:[30,60], speedCap:7 },
    turbineTrip:    { shockChance:0.15, throttleSnapThreshold:10, throttleSnapChance:0.20, recoveryTime:[20,30], speedCap:12 },
    reactorRunaway: { hitChance:0.08, transientRange:3000, transientSus:0.60 },
  },
  torpWeapon:'mk48_adcap', missileStock:0, missileTypes:[], vlsCells:0, vlsWeapon:null,
  isDiesel:false,
  battery:      { drainOnScram:0.0020, chargeRate:0.008 },
  snorkelDepth:12, snorkelNoise:0, snorkelSpeedCap:100,
  hasTowedArray:true,
  masts:mastsUS,
  esmRange:12000, radarRange:7000,
  sonar: {
    bowHullHalfAngleDeg:     150,
    baffleHalfAngleDegBase:   15,
    baffleHalfAngleDegPerKt:   1.5,
    baffleHalfAngleDegMax:    45,
    baffleRolloffDeg:         20,
    enemyBaffleBase:          20,
    enemyBafflePerKt:          2.0,
    enemyBaffleMax:           55,
  },
};

// ── Playable vessel definitions ───────────────────────────────────────────────
export const VESSELS = [
  { ...sh, key:'688', name:'USS DALLAS', vesselClass:'LOS ANGELES CLASS (FLIGHT I)', nation:'US', difficulty:'medium', accelTau:45, decelTau:30,
    flavour:'Cold War workhorse. Balanced across all systems.',
    lore:[
      'SSN-700 · Commissioned 1981 · Los Angeles class Flight I — 62 boats built over 22 years',
      'The backbone of the Cold War US submarine fleet. Balanced and capable across all systems.',
      'Conducted extensive intelligence patrols in Soviet home waters throughout the 1980s.',
      'Standard loadout: 26 MK-48 ADCAP torpedoes plus Harpoon anti-ship missiles.',
      'Immortalised in The Hunt for Red October. Still in frontline service into the 2000s.',
      'Recommended for new players who want capable all-round performance with no major weaknesses.',
    ],
    divingLimitM:400, sonarSuite:'AN/BQQ-5D', sonarQuality:0.85,
    divingLimit:400, safeDivingDepth:300, designDepth:450, maxDepth:480, crushDepth:520,
    torpWeapon:'mk48_adcap', towedArray:'TB-16 / TB-23',
    r:28, hpMax:100, hitR:30, speedMaxKts:20, flankKts:28,
    noiseFloor:0.040, flankNoiseBoost:0.42,
    torpTubes:4, torpStock:26, magazineRack:22, torpReloadTime:28, cmStock:12,
    vlsCells:0, vlsWeapon:null, missileStock:8,
    missileTypes:['harpoon','tasm','tlam','subroc','mk67_slmm','mk60_captor'],
    cavitationKtsRef:18, speedDeafness:{ startKts:4, fullDeafKts:10 } },

  { ...sh, key:'688i', name:'USS PROVIDENCE', vesselClass:'LOS ANGELES CLASS (IMPROVED)', nation:'US', difficulty:'medium', accelTau:45, decelTau:30,
    flavour:'Improved 688 with VLS. TLAM cruise missile strike capability.',
    lore:[
      'SSN-719 · Commissioned 1985 · Los Angeles Improved (688i) — first boat fitted with VLS',
      'The 688i upgrade added 12 vertical launch tubes for BGM-109 Tomahawk cruise missiles.',
      'Identical hull and internal layout to the Flight I boats.',
      'VLS cells are external to the pressure hull — no impact on internal compartmentation.',
      'Harpoon phased out on 688i. SUBROC and TASM retired before this variant entered service.',
      'Recommended for players who want the 688 platform with added land-attack strike from VLS.',
    ],
    divingLimitM:400, sonarSuite:'AN/BQQ-5D', sonarQuality:0.85,
    divingLimit:400, safeDivingDepth:300, designDepth:450, maxDepth:480, crushDepth:520,
    torpWeapon:'mk48_adcap', towedArray:'TB-16 / TB-23',
    r:28, hpMax:100, hitR:30, speedMaxKts:20, flankKts:28,
    noiseFloor:0.040, flankNoiseBoost:0.42,
    torpTubes:4, torpStock:26, magazineRack:22, torpReloadTime:28, cmStock:12,
    vlsCells:12, vlsWeapon:'tlam', missileStock:4,
    missileTypes:['tlam','mk67_slmm','mk60_captor'],
    cavitationKtsRef:18, speedDeafness:{ startKts:4, fullDeafKts:10 } },

  { ...sh, key:'trafalgar', name:'HMS TRAFALGAR', vesselClass:'TRAFALGAR CLASS', nation:'UK', difficulty:'medium', masts:mastsUK, accelTau:40, decelTau:25, turnRateDeg:2.0,
    flavour:'Pump-jet propulsor — dramatically quieter at speed.',
    lore:[
      'S107 · Commissioned 1983 · Trafalgar class — lead boat of 7',
      'First Royal Navy SSN fitted with a pump-jet propulsor instead of a conventional screw.',
      'The pump-jet delivers a marked acoustic advantage at speed — a critical tactical asset.',
      'Deployed throughout the Cold War and beyond. Gulf War 1991. Kosovo 1999.',
      'Armed with SPEARFISH — one of the fastest and hardest-hitting torpedoes ever deployed at 70+ knots.',
      'Recommended for players who favour aggressive high-speed tactics with superior stealth.',
    ],
    divingLimitM:400, sonarSuite:'TYPE 2076', sonarQuality:0.88,
    divingLimit:400, safeDivingDepth:300, designDepth:450, maxDepth:480, crushDepth:520,
    torpWeapon:'spearfish', towedArray:'TYPE 2026',
    r:26, hpMax:100, hitR:28, speedMaxKts:18, flankKts:26,
    noiseFloor:0.032, flankNoiseBoost:0.30,
    torpTubes:5, torpStock:30, magazineRack:25, torpReloadTime:30, cmStock:12,
    missileStock:6, missileTypes:['sub_harpoon','tlam','stonefish'],
    cavitationKtsRef:20, speedDeafness:{ startKts:5, fullDeafKts:12 },
    sonar:{ ...sh.sonar, bowHullHalfAngleDeg:155, baffleHalfAngleDegBase:13 } },

  { ...sh, key:'swiftsure', name:'HMS SWIFTSURE', vesselClass:'SWIFTSURE CLASS', nation:'UK', difficulty:'medium', masts:mastsUK, accelTau:50, decelTau:35, turnRateDeg:2.0,
    flavour:'Older design, fewer weapons. Quieter than 688i at depth.',
    lore:[
      'S126 · Commissioned 1973 · Swiftsure class — lead boat of 6',
      'Direct predecessor to the Trafalgar boats. Conventional screw — noisier at speed.',
      'Deeper diving and faster than the preceding Valiant class. Good below-layer endurance.',
      'Armed with TIGERFISH — wire-guided and reliable but substantially slower than SPEARFISH.',
      'Smaller weapons magazine and older systems make this a harder boat to fight effectively.',
      'Recommended for experienced players who want a challenge with older British equipment.',
    ],
    divingLimitM:350, sonarSuite:'TYPE 2020', sonarQuality:0.76,
    divingLimit:350, safeDivingDepth:260, designDepth:400, maxDepth:430, crushDepth:465,
    torpWeapon:'tigerfish', towedArray:'TYPE 2026',
    r:24, hpMax:90, hitR:26, speedMaxKts:18, flankKts:25,
    noiseFloor:0.038, flankNoiseBoost:0.38,
    torpTubes:5, torpStock:20, magazineRack:15, torpReloadTime:32, cmStock:10,
    missileStock:6, missileTypes:['sub_harpoon','stonefish'],
    cavitationKtsRef:17, speedDeafness:{ startKts:4, fullDeafKts:11 },
    sonar:{ ...sh.sonar, baffleHalfAngleDegBase:18 } },

  { ...sh, key:'seawolf', name:'USS CONNECTICUT', vesselClass:'SEAWOLF CLASS', nation:'US', difficulty:'easy', accelTau:35, decelTau:25, turnRateDeg:1.8,
    flavour:'Post-Cold War overkill. Eight tubes, extreme depth, maximum firepower.',
    lore:[
      'SSN-22 · Commissioned 1998 · Seawolf class — only 3 completed before cancellation',
      'Designed expressly to hunt Akula-class SSNs in Soviet home waters. Overbuilt for the task.',
      'Eight torpedo tubes, 50-weapon magazine, 480m depth limit. The best submarine ever built.',
      'AN/BQQ-5E sonar and TB-29A towed array — the most capable sensor suite in the fleet.',
      'Post-Cold War budget cuts killed the programme. The war it was designed for never came.',
      'Recommended for players who want maximum capability. The easy classification is by design.',
    ],
    divingLimitM:480, sonarSuite:'AN/BQQ-5E', sonarQuality:0.95,
    divingLimit:480, safeDivingDepth:365, designDepth:530, maxDepth:560, crushDepth:605,
    torpWeapon:'mk48_adcap', towedArray:'TB-16 / TB-29A',
    r:32, hpMax:120, hitR:35, speedMaxKts:20, flankKts:35,
    noiseFloor:0.025, flankNoiseBoost:0.28,
    torpTubes:8, torpStock:50, magazineRack:42, torpReloadTime:22, cmStock:16,
    missileStock:8, missileTypes:['harpoon','tasm','tlam','mk67_slmm','mk60_captor'],
    cavitationKtsRef:22, speedDeafness:{ startKts:5, fullDeafKts:13 },
    sonar:{ ...sh.sonar, bowHullHalfAngleDeg:158, baffleHalfAngleDegBase:12 } },

  { ...sh, key:'type209', name:'U-36', vesselClass:'TYPE 209', nation:'DE', difficulty:'expert', accelTau:60, decelTau:20, turnRateDeg:2.8,
    flavour:'Diesel-electric. Near-silent on battery. One wrong move and you are out of torpedoes.',
    lore:[
      'U-36 · Commissioned 1997 · Deutsche Marine — Type 209/1400mod variant',
      'Diesel-electric propulsion: near-silent on battery, but snorkel ops broadcast your position.',
      'The most exported submarine design in history — operated by more than 14 navies worldwide.',
      'Armed with SST-4 and SUT wire-guided torpedoes. Reliable but slower than NATO designs.',
      'Maximum depth 250m. The thermal layer is your primary tactical tool — use it constantly.',
      'Expert rating. Battery management and snorkel exposure are unforgiving. One error is fatal.',
    ],
    divingLimitM:250, sonarSuite:'ATLAS DBQS-21', sonarQuality:0.65,
    divingLimit:250, safeDivingDepth:190, designDepth:280, maxDepth:300, crushDepth:325,
    torpWeapon:'sst4', towedArray:'PRS-3 PASSIVE',
    r:18, hpMax:70, hitR:20, speedMaxKts:8, flankKts:12,
    noiseFloor:0.018, flankNoiseBoost:0.55,
    torpTubes:8, torpStock:14, magazineRack:6, torpReloadTime:35, cmStock:8,
    missileStock:4, missileTypes:['sm39'],
    cavitationKtsRef:11, speedDeafness:{ startKts:6, fullDeafKts:14 },
    isDiesel:true, hasTowedArray:false,
    battery:{ drainPerKt:0.00014, chargeRate:0.003, surfaceChargeRate:0.005 },
    snorkelNoise:0.35, snorkelSpeedCap:5,
    sonar:{ ...sh.sonar, baffleHalfAngleDegBase:12, baffleHalfAngleDegPerKt:1.0 } },

  // ── DEV TEST SUBMARINE ──────────────────────────────────────────────────
  // Not a real vessel. Infinite depth, fast speed, no weapons. For testing
  // bathymetry, grounding, ocean model, and world-scale navigation.
  { ...sh, key:'dev_sub', name:'TEST VEHICLE', vesselClass:'DEV TEST PLATFORM', nation:'US', difficulty:'easy',
    accelTau:10, decelTau:5, turnRateDeg:5.0, noPropulsionCasualties:true,
    flavour:'Development test submarine. Infinite depth. No weapons.',
    lore:['Test platform for development and debugging. Not a real submarine.'],
    divingLimitM:99999, sonarSuite:'NONE', sonarQuality:0.50,
    divingLimit:99999, safeDivingDepth:99999, designDepth:99999, maxDepth:99999, crushDepth:99999,
    torpWeapon:'mk48_adcap', towedArray:'NONE',
    r:20, hpMax:200, hitR:22, speedMaxKts:40, flankKts:60,
    noiseFloor:0.010, flankNoiseBoost:0.20,
    torpTubes:0, torpStock:0, magazineRack:0, torpReloadTime:99, cmStock:0,
    vlsCells:0, vlsWeapon:null, missileStock:0, missileTypes:[],
    cavitationKtsRef:99, speedDeafness:{ startKts:99, fullDeafKts:99 },
    depthTau:2.0, depthRateMax:10.0, // very fast depth changes
    hasTowedArray:false, masts:mastsUS },
];
